USE phitron;
DROP TABLE IF EXISTS Student;

CREATE TABLE Student(
    Roll CHAR(4) PRIMARY KEY,
    Name VARCHAR(50),
    Marks DOUBLE
);

INSERT INTO Student 
(Roll, Name, Marks) VALUES(1, "Showmik", 88.88);

INSERT INTO Student 
(Roll, Name) VALUES(2, "Devdut");

SET SQL_SAFE_UPDATES = 0;

UPDATE Student
SET Name = "SHOWMIK SHARMA"
WHERE Roll = 1;
SET SQL_SAFE_UPDATES = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM Student
WHERE Roll = 1;
SET SQL_SAFE_UPDATES = 1;

DROP TABLE Student;