DROP DATABASE IF EXISTS SHOWMIK;
CREATE DATABASE SHOWMIK;

USE SHOWMIK;
DROP TABLE IF EXISTS STUDENTS;
CREATE TABLE STUDENTS (
    ROLL CHAR(4) PRIMARY KEY,
    NAME VARCHAR(50),
    MARKS DOUBLE,
    CGPA VARCHAR(4)
);

INSERT INTO STUDENTS
(ROLL, NAME, MARKS, CGPA)
VALUES(1, "SHOWMIK", 99.88, "A+");

SET SQL_SAFE_UPDATES = 0;
UPDATE STUDENTS
SET NAME = "SHOWMIK SHARMA DINOBOUNHDU"
WHERE ROLL = 1;
SET SQL_SAFE_UPDATES = 1;