-- ALL EMPLOYEES:
SELECT *
FROM EMPLOYEES
ORDER BY SALARY DESC;

-- ONLY SALARY:
SELECT DISTINCT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

-- PROGRAM OF THIRD HIGHEST SALARY: 
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < (
	SELECT MAX(SALARY)
    FROM EMPLOYEES
    WHERE SALARY < (
		SELECT MAX(SALARY)
        FROM EMPLOYEES
        )
	);
   
   -- THIRD HIGHEST SALARY: 
SELECT * 
FROM EMPLOYEES
WHERE SALARY = (
	SELECT MAX(SALARY)
	FROM EMPLOYEES
	WHERE SALARY < (
		SELECT MAX(SALARY)
		FROM EMPLOYEES
		WHERE SALARY < (
			SELECT MAX(SALARY)
			FROM EMPLOYEES
			)
		)
	);