SELECT *
FROM EMPLOYEES;

-- HIRED AFTER STEVEN:
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE HIRE_DATE > (
			SELECT HIRE_DATE
            FROM EMPLOYEES
            WHERE FIRST_NAME = "STEVEN"
			AND LAST_NAME = "KING"
            );
