SELECT *
FROM DEPARTMENTS;

SELECT*
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;

-- IT DEPT:
SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;

-- MARKETING DEPT:
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20;

-- WORK OF CTE
WITH AVGIT AS
(
	-- IT DEPT:
	SELECT AVG(SALARY) AS SAL1
	FROM EMPLOYEES
	WHERE DEPARTMENT_ID = 60
),

MAXMRK AS
(
	-- MARKETING DEPT:
	SELECT MAX(SALARY) AS SAL2
	FROM EMPLOYEES
	WHERE DEPARTMENT_ID = 20
)

SELECT *
FROM EMPLOYEES
WHERE SALARY > (SELECT SAL1 FROM AVGIT) AND SALARY < (SELECT SAL2 FROM MAXMRK);
