DROP DATABASE IF EXISTS CONSTRAINTS;
CREATE DATABASE CONSTRAINTS;

USE CONSTRAINTS;
DROP TABLE IF EXISTS STUDENT;

-- CONSTAINTS POSSIBLE PROCESS WAY--
-- PROCESS -01 : 
CREATE TABLE STUDENT(
	ROLL CHAR(4) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    ADDRESS VARCHAR(250),
    AGE INT CHECK(AGE > 10)
);

-- PROCESS -02:
CREATE TABLE STUDENT_2(
	ROLL CHAR(4),
	NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50),
    ADDRESS VARCHAR(250),
    AGE INT,
    
    PRIMARY KEY(ROLL),
    UNIQUE (EMAIL),
    CHECK (AGE > 10)
);

-- PROCESS -03:
CREATE TABLE STUDENT_3(
	ROLL CHAR(4),
	NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50),
    ADDRESS VARCHAR(250),
    AGE INT,
    
    CONSTRAINT PRIMARY KEY(ROLL),
    CONSTRAINT UNIQUE (EMAIL),
    CONSTRAINT CHECK (AGE > 10)
);

-- PROCESS -04:
CREATE TABLE STUDENT_4(
	ROLL CHAR(4),
	NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50),
    ADDRESS VARCHAR(250),
    AGE INT,
    
    CONSTRAINT PK_RULE PRIMARY KEY(ROLL),
    CONSTRAINT UQ_RULE UNIQUE (EMAIL),
    CONSTRAINT CK_RULE CHECK (AGE > 10)
);