SELECT *
FROM employees;

SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;

-- SELECT DEPARTMENT_ID, COUNT(employee_id)
-- or
SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;