SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID != 20
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY) > 5000;

SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID != 20
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 5000;

SELECT DEPARTMENT_ID, MAX(SALARY) AS sal
FROM EMPLOYEES
WHERE DEPARTMENT_ID != 20
GROUP BY DEPARTMENT_ID
HAVING sal > 5000;