-- FIRST MAX SALARY FIND OUT: 
SELECT MAX(SALARY)
FROM EMPLOYEES;

-- NEXT COMPARE WITH MAX SALRY WITH SALARY:
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < (
	SELECT MAX(SALARY)
    FROM EMPLOYEES
    );
    
-- NOW DOING THAT IN SUBQUERY
SELECT *
FROM EMPLOYEES
WHERE SALARY = (
	SELECT MAX(SALARY)
    FROM EMPLOYEES
    WHERE SALARY < (
		SELECT MAX(SALARY)
        FROM EMPLOYEES
        )
	);