-- SALARY CHECK:
SELECT *
FROM EMPLOYEES;

-- HIGHEST SALARY + SAME SALARY AGAIN & AGAIN COMING OR NOT CHECK:
SELECT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

-- TO STOP SAME VALUE AGAIN & AGAIN:
SELECT DISTINCT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

-- NOW FIND OUT THE SECOND HIGEST SALARY:
SELECT DISTINCT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 1,1;

-- OR:
SELECT DISTINCT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 1
OFFSET 1;


-- NOW DOING THIS IN A SUBQUERY:
SELECT *
FROM EMPLOYEES
WHERE SALARY = (
	SELECT DISTINCT SALARY
    FROM EMPLOYEES
    ORDER BY SALARY DESC
    LIMIT 1
    OFFSET 1
);