-- FULL EMPLOYEES CHECK + THEIR SALARY 
SELECT *
FROM EMPLOYEES;

-- NOW COMPARE:
SELECT *
FROM EMPLOYEES AS EMP
WHERE SALARY > (
	SELECT SALARY
    FROM EMPLOYEES AS MGR
    WHERE EMP.MANAGER_ID = MGR.EMPLOYEE_ID
    );