SELECT*
FROM EMPLOYEES;

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY > 15000;

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;

-- UNION BOTH OF THEM:
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY > 10000
INTERSECT
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;

-- OR:
-- UNION BOTH OF THEM:
SELECT *
FROM EMPLOYEES
WHERE SALARY > 10000
INTERSECT
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;