SELECT *
FROM JOBS;

SELECT *
FROM EMPLOYEES
WHERE JOB_ID = (
	SELECT JOB_ID
    FROM JOBS
    WHERE JOB_TITLE = "PROGRAMMER");
    
SELECT SUM(SALARY)
FROM EMPLOYEES
WHERE JOB_ID = (
	SELECT JOB_ID
    FROM JOBS
    WHERE JOB_TITLE = "PROGRAMMER");