SELECT * 
FROM DEPARTMENTS;

SELECT COUNT(*) 
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;

SELECT COUNT(*) 
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
	SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
    WHERE DEPARTMENT_ID = 60);
    
SELECT COUNT(*) AS MEMBERS
FROM EMPLOYEES 
WHERE DEPARTMENT_ID = (
	SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
    WHERE DEPARTMENT_ID = 60);