SELECT*
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 144;

SELECT*
FROM EMPLOYEES
WHERE SALARY < 2500;

-- SUB QUERRY JE KARA KARA 2500 BA ID 144 THEKE TAKA KOM PAI AND 144 NO ID ER SALARY REPRESENT KORBE:
SELECT *
FROM EMPLOYEES
WHERE SALARY < (
	SELECT SALARY
	FROM EMPLOYEES
	WHERE EMPLOYEE_ID = 144
    );