SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT 
	EMPLOYEES.FIRST_NAME, 
    EMPLOYEES.SALARY, 
	(SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID) - EMPLOYEES.SALARY
FROM EMPLOYEES 
	JOIN DEPARTMENTS 
		ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID


-- SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 10;